name: build-and-test
on:
  push:
    branches: [ master ]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: NVMRC=$(cat .nvmrc)
      - name: Use .nvmrc node version
        uses: actions/setup-node@v1
        with:
          node-version: ${NVMRC}
      - run: npm install -g yarn
      - run: node -v
      - run: yarn
      - run: yarn build
      - run: yarn lint
      - run: yarn test
      - run: yarn codecov
      
